using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace Pegasus_backend.Controllers.MobileControllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ChatController : ControllerBase
    {
        private readonly IHubContext<Chatroom> _hub;

        public ChatController(IHubContext<Chatroom> hub)
        {
            _hub = hub;
        }

        public IActionResult Get()
        {
            // server is sending data to the client only
            // sending generated data to all subscribed clients on the Transferchatdata event
            // every client if has a listener on the transferchatdata event, will receive a data generated by the DataManager
            var timerManager = new TimeManager(() => _hub.Clients.All.SendAsync("Transferchatdata", DataManager.GetData()));
            return Ok(new {Message = "Request Completed"});
        }
    }
}